services:
  - type: web
    name: stochastic-storage-var
    env: python
    plan: free
    rootDir: StorageIQ_Dashboard
    buildCommand: pip install fastapi "uvicorn[standard]"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
